/robot_news_station_glskard:
  ros__parameters:
    robot_name: "glskard"
/robot_news_station_bb8:
  ros__parameters:
    robot_name: "bb8"
  
/robot_news_station_daneel:
  ros__parameters:
    robot_name: "daneel"
  